name: kdemy
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.0
  flutter_phoenix: ^1.0.0
  animation_wrappers: ^0.0.4
  percent_indicator: ^3.0.1
  shared_preferences: ^2.0.5
  google_mobile_ads: ^0.13.2
  getwidget: ^2.0.4
  video_player: ^2.0.2
  flick_video_player:
  provider: ^5.0.0
  wakelock: ^0.5.0+2
  universal_html: ^2.0.8
  visibility_detector: ^0.2.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_launcher_name:
  name: "kdemy"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/appIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/Images/
    - assets/SocialIcons/
    - assets/TopCategories/

  fonts:
    - family: Sans
      fonts:
        - asset: fonts/Sans/GoogleSans-Bold.ttf
        - asset: fonts/Sans/GoogleSans-BoldItalic.ttf
        - asset: fonts/Sans/GoogleSans-Italic.ttf
        - asset: fonts/Sans/GoogleSans-Medium.ttf
        - asset: fonts/Sans/GoogleSans-Regular.ttf
        - asset: fonts/Sans/GoogleSans-MediumItalic.ttf



